### ISSUE TITLE
Consistent Fingerprint

### ISSUE THREAD

**Issue by Ehsan-U** [daijro/hazetunnel#1]
First of all, Thanks for this amazing tool !

Recently, I used `Browserforge` with `Playwright` on a popular social media site to create a `Session`. I have saved the fingerprint and now want to use it with `Requests` using `Hazetunnel`. 
Currently `Hazetunnel` generates a random fingerprint each time based on the `User-Agent`, Is it possible to replicate the exact fingerprint that generated previouly during `Session` ?

**Comment by daijro** [comment]
Hi, I think you may be confusing **TLS fingerprints** with **Browser fingerprints**. Let me clarify:

**Browser fingerprints** (as generated by `FingerprintGenerator`) are characteristics of a browser gathered through JavaScript. They include details like screen size, installed plugins, and fonts. Since `requests` is a network-only library and doesn't execute JavaScript, it cannot use browser _fingerprints_. It can only use network _headers_:

```py
headers = HeaderGenerator()           # Create the Browserforge header generator
session = requests.Session()          # Build the requests session
session.headers = headers.generate()  # Set the requests session headers
```

**TLS fingerprints** are used to identify the browser and version based on the protocols used in the network request, not JavaScript properties. Hazetunnel doesn’t generate random fingerprints. Instead, it modifies the protocols in the request, to make your request appear to be coming from the browser specified in your headers:

```py
from hazetunnel import HazeTunnel
from browserforge.headers import HeaderGenerator
import requests

# Build a requests session with Chrome headers
headers = HeaderGenerator()
session = requests.Session()
session.headers = headers.generate(browser='chrome')  # Set the requests session headers

# Hazetunnel will modify the request to use Chrome's networking protocols.
with HazeTunnel() as proxy:
  # Send the request
  resp = session.get(
      url='https://example.com',
      proxies={'https': proxy.url},
      verify=proxy.cert
  ).text
```

In this example, Hazetunnel will use Chrome's network protocols, because Chrome headers are being sent in the request.

You can simply pass your headers to the request for Hazetunnel to override the TLS fingerprint.

Feel free to send your code samples here, I'd be happy to help explain it!
